<?php
/**
 * Implements hook_views_post_execute().
 *
 * If there is a pager display output rel links
 *
 * @see https://support.google.com/webmasters/answer/1663744?hl=en
 *
 * @param $view
 */
function metatag_pagination_views_post_execute(&$view) {
  // @todo - this solution only works if we can expect one pager per page.
  if ($view->display[$view->current_display]->handler->use_pager()) {
    $current_page = $view->query->pager->current_page;
    $items_per_page = $view->query->pager->options['items_per_page'];
    $last_item_viewed = ($current_page * $items_per_page) + $items_per_page;
    // Prepare link rel=prev if current page > 0.
    if ($current_page > 0) {
      if ($current_page > 1) {
        $parameters = array(
          'page' => $current_page - 1,
        );
      }
      else {
        $parameters = array();
      }
      $query = drupal_get_query_parameters($parameters, array());
      if ($query_pager = pager_get_query_parameters()) {
        $query = array_merge($query, $query_pager);
      }
      $head_link = array(
        'rel' => 'prev',
        'href' => url(
          $_GET['q'],
          array(
            'query' => $query,
          )
        ),
      );
      drupal_add_html_head_link($head_link);
    }
    // Prepare link rel=next if more pages available.
    if ($view->query->pager->total_items > $last_item_viewed) {
      $parameters = array(
        'page' => $current_page + 1,
      );
      $query = drupal_get_query_parameters($parameters, array());
      if ($query_pager = pager_get_query_parameters()) {
        $query = array_merge($query, $query_pager);
      }
      $head_link = array(
        'rel' => 'next',
        'href' => url(
          $_GET['q'],
          array(
            'query' => $query,
          )
        ),
      );
      drupal_add_html_head_link($head_link);
    }
  }
}
